Function Clear-LSScrubFiles {
    <#
.SYNOPSIS
Removes files generated by Invoke-LSScrub related to $LogFileName
.DESCRIPTION
.PARAMETER LogFileName
.EXAMPLE
.EXAMPLE
.INPUTS
    [string]
.OUTPUTS
.NOTES
    Author:  Paul Harrison
#>
    Param(
        [Parameter(Mandatory = $true, 
            ValueFromPipeline = $true,
            Position = 0)]
        [ValidateNotNullOrEmpty()]
        $LogFileName
    )
    Remove-Item -Force ($LogFileName + "-IPScrubbed"), ($LogFileName + "-IPScrubbed-Scrubbed"), ($LogFileName + "-IPsKey"), ($LogFileName + "-BadWordKey"), ($LogFileName + "-Scrubbed") -ea 0
}