Function Invoke-LSBadWordScrub {
    <#
.SYNOPSIS

.DESCRIPTION
.PARAMETER LogFileName
.PARAMETER BadWordFile
The name of the BadWordFile generated by 
.PARAMETER BadWordKeyFile
The name of the BadWordKeyFile generated by New-LSBadWords
.PARAMETER OriginalLogFileName
The name of the log file to scrub
.EXAMPLE
.EXAMPLE
.INPUTS
    [string]
.OUTPUTS
.NOTES
    Author:  Paul Harrison
#>
    Param
    (
        # LogFileName The path and name of the log file to scrub
        [Parameter(Mandatory = $true, 
            ValueFromPipeline = $true,
            Position = 0)]
        [ValidateNotNullOrEmpty()]
        $LogFileName,
        [Parameter(Mandatory = $true, 
            ValueFromPipeline = $false,
            Position = 1)]
        [ValidateNotNullOrEmpty()]
        $BadWordFile,
        [Parameter(Mandatory = $true, 
            ValueFromPipeline = $false,
            Position = 2)]
        [ValidateNotNullOrEmpty()]
        $BadWordKeyFile,
        [Parameter(Mandatory = $true,
            ValueFromPipeline = $false,
            Position = 3)]
        [ValidateNotNullOrEmpty()]
        $OriginalLogFileName
    )

    Find-LSBadWords -LogFileName $LogFileName -BadWordFile $BadWordFile -BadWordKeyFile $BadWordKeyFile
    New-LSBadWords -LogFileName $LogFileName -BadWordFile $BadWordFile -BadWordKeyFile $BadWordKeyFile
    Set-LSBadWords -LogFile $LogFileName -BadWordsKeyList $BadWordKeyFile -BadWordKeyFile $BadWordKeyFile -OutputFileName ($OriginalLogFileName + "-Scrubbed")


}
